name: Packer Build GCP

on:
  workflow_dispatch:
  

permissions:
  contents: read
  id-token: write   # REQUIRED for OIDC

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          curl -fsSL -o packer.zip https://releases.hashicorp.com/packer/1.15.0/packer_1.15.0_linux_amd64.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/372824992171/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "packer-github-sa@packer-image-project.iam.gserviceaccount.com"

      - name: Run Packer
        run: |
          packer init gcp-ubuntu.pkr.hcl
          packer validate gcp-ubuntu.pkr.hcl
          packer build gcp-ubuntu.pkr.hcl
